eid data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-1703030000_100/-/px-x-1703030000_100.px/table/tableViewLayout2/ $\newline$
2025 population data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-0102020000_202/-/px-x-0102020000_202.px/
$\newline$
Note: this data analysis was done without any help from AI.

In [50]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [51]:
cantons_df = pd.read_csv("cantons_data.csv")
eid_df = pd.read_csv("eid_votation.csv")

In [52]:
col = ["Year", "Canton", "Age", "Sex", "Count", "Death", "Immigration", "Swiss citizenship acquisition"]
cantons_df = cantons_df[col]

In [53]:
cantons_df.head()

,Year,Canton,Age,Sex,Count,Death,Immigration,Swiss citizenship acquisition
0,2025,Suisse,18 ans,Sexe - total,67503,17,355,886
1,2025,Suisse,19 ans,Sexe - total,67525,19,430,839
2,2025,Suisse,20 ans,Sexe - total,67636,21,371,661
3,2025,Suisse,21 ans,Sexe - total,67940,25,376,486
4,2025,Suisse,22 ans,Sexe - total,66647,24,459,388

In [54]:
cantons_df["Canton"].unique()

array(['Suisse', 'Z�rich', 'Bern / Berne', 'Luzern', 'Uri', 'Schwyz',
       'Obwalden', 'Nidwalden', 'Glarus', 'Zug', 'Fribourg / Freiburg',
       'Solothurn', 'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Graub�nden / Grigioni / Grischun', 'Aargau', 'Thurgau', 'Ticino',
       'Vaud', 'Valais / Wallis', 'Neuch�tel', 'Gen�ve', 'Jura',
       'Sans indication'], dtype=object)

In [56]:
def fix_cantons(cantons_df):
    cantons_df = cantons_df.replace('Z�rich','Zurich')
    cantons_df = cantons_df.replace('Bern / Berne','Berne')
    cantons_df = cantons_df.replace('Fribourg / Freiburg','Fribourg')
    cantons_df = cantons_df.replace('Graub�nden / Grigioni / Grischun','Grischun')
    cantons_df = cantons_df.replace('Valais / Wallis','Valais')
    cantons_df = cantons_df.replace('Neuch�tel','Neuchatel')
    cantons_df = cantons_df.replace('Gen�ve','Geneve')

    return cantons_df

cantons_df = fix_cantons(cantons_df)
eid_df = fix_cantons(eid_df)

In [57]:
cantons_df["Canton"].unique()

array(['Suisse', 'Zurich', 'Berne', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
       'Nidwalden', 'Glarus', 'Zug', 'Fribourg', 'Solothurn',
       'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Grischun', 'Aargau', 'Thurgau', 'Ticino', 'Vaud', 'Valais',
       'Neuchatel', 'Geneve', 'Jura', 'Sans indication'], dtype=object)

In [59]:
eid_df.head()

,Canton,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,Yes %
0,Suisse,5641040,2796897,49.58,2747948,1384586,1363362,50.39
1,Zurich,976490,509297,52.16,503923,274702,229221,54.51
2,Berne,750745,358855,47.80,354158,171771,182387,48.50
3,Luzern,288363,153604,53.27,151603,80261,71342,52.94
4,Uri,27226,12731,46.76,12567,5109,7458,40.65

In [60]:
cantons_df.head()

,Year,Canton,Age,Sex,Count,Death,Immigration,Swiss citizenship acquisition
0,2025,Suisse,18 ans,Sexe - total,67503,17,355,886
1,2025,Suisse,19 ans,Sexe - total,67525,19,430,839
2,2025,Suisse,20 ans,Sexe - total,67636,21,371,661
3,2025,Suisse,21 ans,Sexe - total,67940,25,376,486
4,2025,Suisse,22 ans,Sexe - total,66647,24,459,388

In [ ]:
age_groups = [range(18, 24), range(24,30), range(30, 36), range(36, 42), range(42, 48), range(48, 53), range(54, 60), range(60, 66)]

def age_sort(df, age_groups):
    # group by ages to count population groups
    for age_group in age_groups:
        new_string = str(age_group[0]) + " - " + str(age_group[-1])
        for age in age_group:
            age_string = str(age) + " ans"
            df = df.replace(age_string, new_string)
        
        # sum count of population
        df.groupby("Age")[df["Age"] == new_string].sum()